<?php

require_once '/var/www/html/xml_generator/classes/table/Tabelle.php';

/**
 * Test class for Tabelle.
 * Generated by PHPUnit on 2015-05-25 at 00:27:58.
 */
class TabelleTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Tabelle
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Tabelle(6,6);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetMaxX().
     */
    public function testGetMaxX()
    {
        $this->assertEquals(6, $this->object->getMaxX());
    }

    /**
     * @todo Implement testGetMaxY().
     */
    public function testGetMaxY()
    {
        $this->assertEquals(6, $this->object->getMaxY());
    }

    /**
     * @todo Implement testAddCell().
     */
    public function testAddCell()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );

    }

    /**
     * @todo Implement testGetCell().
     */
    public function testGetCell()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );

    }

    /**
     * @todo Implement testGetCells().
     */
    public function testGetCells()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );

    }

    /**
     * @todo Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testToHTML().
     */
    public function testToHTML()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testOutputXML().
     */
    public function testOutputXML()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDeleteColl().
     */
    public function testDeleteColl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDeleteRow().
     */
    public function testDeleteRow()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCleanUp().
     */
    public function testCleanUp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAppendCellofRow().
     */
    public function testAppendCellofRow()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testPrependCellofRow().
     */
    public function testPrependCellofRow()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDeleteCell().
     */
    public function testDeleteCell()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
