<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-28 at 18:44:22.
 */
class XMLProcessorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var XMLProcessor
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new XMLProcessor;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers XMLProcessor::init
     * @todo   Implement testInit().
     */
    public function testInit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLProcessor::output
     * @todo   Implement testOutput().
     */
    public function testOutput() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLProcessor::Absatz
     * @todo   Implement testAbsatz().
     */
    public function testAbsatz() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLProcessor::Berichtsteil
     * @todo   Implement testBerichtsteil().
     */
    public function testBerichtsteil() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLProcessor::Zwischentitel
     * @todo   Implement testZwischentitel().
     */
    public function testZwischentitel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLProcessor::Liste
     * @todo   Implement testListe().
     */
    public function testListe() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLProcessor::Kursiv
     * @todo   Implement testKursiv().
     */
    public function testKursiv() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLProcessor::Bold
     * @todo   Implement testBold().
     */
    public function testBold() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLProcessor::LTitel
     * @todo   Implement testLTitel().
     */
    public function testLTitel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLProcessor::initTabelle
     * @todo   Implement testInitTabelle().
     */
    public function testInitTabelle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLProcessor::Zelle
     * @todo   Implement testZelle().
     */
    public function testZelle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLProcessor::getAlignment
     * @todo   Implement testGetAlignment().
     */
    public function testGetAlignment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLProcessor::getFormat
     * @todo   Implement testGetFormat().
     */
    public function testGetFormat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLProcessor::getZeilentyp
     * @todo   Implement testGetZeilentyp().
     */
    public function testGetZeilentyp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
